name: Build and Push Docker Image

on:
  push:
    paths:
      - 'auth-service/**'
      - '.github/workflows/build-auth.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Set Tag
        id: vars
        run: |
          TAG=$(date +%Y%m%d%H%M)-$(git rev-parse --short HEAD)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        env:
          CR_REGISTRY: crpeotdomuljuu8m735b
          CR_REPOSITORY: auth
          IMAGE_TAG: ${{ steps.vars.outputs.tag }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG ./auth-service
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG